environment:
  JULIA_TZ_VERSION: "2016j"

  matrix:
  - julia_version: 0.6
  - julia_version: 0.7
  - julia_version: 1.0
  - julia_version: latest

matrix:
  allow_failures:
    # Failing due to https://github.com/bicycle1885/EzXML.jl/issues/66
    - julia_version: 0.7
    - julia_version: 1.0
    - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

# Needs: https://github.com/JuliaCI/Appveyor.jl/pull/8
# on_success:
#   - echo "%JL_CODECOV_SCRIPT%"
#   - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
